name: pothole_watch
description: "A mobile application for real-time pothole detection using YOLO and GPS tracking."

# This prevents the package from being accidentally published to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  # --- Icons ---
  cupertino_icons: ^1.0.8

  # --- Mapping & Location ---
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  geolocator: ^14.0.2

  # --- Firebase Services ---
  firebase_core: ^4.4.0
  cloud_firestore: ^6.1.2
  firebase_storage: ^13.0.6

  # --- Camera & AI ---
  image_picker: ^1.2.1
  camera: ^0.11.3+1
  ultralytics_yolo: ^0.2.0
  supabase_flutter: ^2.12.0
  sensors_plus: ^7.0.0
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  # Enables the use of Material Design icons and components.
  uses-material-design: true

  # Registering your custom YOLO model so it's bundled into the APK.
  #assets:
  #  - assets/yolov26_best_float16.tflite
  #  - assets/yolov26_best_float32.tflite