// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJEeAZqg8L7ufW2whNbnEzuKDToqZihiM',
    appId: '1:71841574547:web:e12a5bbf1b20f8e811e766',
    messagingSenderId: '71841574547',
    projectId: 'potholedemo-dbbe0',
    authDomain: 'potholedemo-dbbe0.firebaseapp.com',
    storageBucket: 'potholedemo-dbbe0.firebasestorage.app',
    measurementId: 'G-GNLBFTYQTG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1-pU-x8gZ4higVk10oejrn7AcD1P8dJc',
    appId: '1:71841574547:android:51d3b05f904b7ea811e766',
    messagingSenderId: '71841574547',
    projectId: 'potholedemo-dbbe0',
    storageBucket: 'potholedemo-dbbe0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBliaPwv8DXsJ-p3Vn9pP1dx9AyHImXTiM',
    appId: '1:71841574547:ios:1b70c7e56ec74ba911e766',
    messagingSenderId: '71841574547',
    projectId: 'potholedemo-dbbe0',
    storageBucket: 'potholedemo-dbbe0.firebasestorage.app',
    iosBundleId: 'com.example.potholeWatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBliaPwv8DXsJ-p3Vn9pP1dx9AyHImXTiM',
    appId: '1:71841574547:ios:1b70c7e56ec74ba911e766',
    messagingSenderId: '71841574547',
    projectId: 'potholedemo-dbbe0',
    storageBucket: 'potholedemo-dbbe0.firebasestorage.app',
    iosBundleId: 'com.example.potholeWatch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJEeAZqg8L7ufW2whNbnEzuKDToqZihiM',
    appId: '1:71841574547:web:c5fc87aa393901e211e766',
    messagingSenderId: '71841574547',
    projectId: 'potholedemo-dbbe0',
    authDomain: 'potholedemo-dbbe0.firebaseapp.com',
    storageBucket: 'potholedemo-dbbe0.firebasestorage.app',
    measurementId: 'G-585W70V7X6',
  );
}
